[Fix] Paged KVCache forward shape (#1710)
Prior to this PR, if we do multiple round chat with Llama-2-q4f16_1,
we would run into the error below due to shape mismatch
```
  File "/home/cfruan/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc", line 725
TVMError: Check failed: total_seq_length == qkv_data->shape[0] (68 vs. 38) :
```

This PR fixes it.