[Bug fix] Fix build model api return value (#621)
Currently, if the specific workflow does not produce a corresponding
path, the `build_model` API would run into an error.

For instance, if we are reusing the cache, we would not need
`args.params_path`, hence running into error when returning at
`build_model`:
```
AttributeError: 'Namespace' object has no attribute 'params_path'
```

Similarly, depending on the arguments when building, the paths we want
to return may or may not apply.