Fix windows build again (#902)
Following up with the previous commit, MSVC is still unhappy saying:

```
D:\a\package\package\mlc-llm\cpp\llm_chat.cc(209,1): error C2738: 'operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': is ambiguous or is not a member of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\fstream(29,23): message : see declaration of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
D:\a\package\package\mlc-llm\cpp\llm_chat.cc(210,1): error C2738: 'operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': is ambiguous or is not a member of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\fstream(29,23): message : see declaration of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
```

Given that `operator std::string()` does not seem properly supported in
MSVC, I am changing to the `string()` method as documented in
[cppreference](https://en.cppreference.com/w/cpp/filesystem/path/string).